# Grid
#
# We don't actually use a full blown grid on our sites but we do use a few
# grid quality helpers.
#
# @constrained: The size the site will grow to at max-width
# @container: The size the content will grow to at max-width
# @gutter: The space we will have between content sitting next to each other

constrained: 1700px
container: 1180px
gutter: 30px
